### PR TITLE
Added bower and updated the README

### PR DESCRIPTION
**Pull request by jfeigel**
Not sure if the tag will come across in the Pull Request, but after the tag has been added run this from your command line to register it with Bower:

```
bower register bzm-range-slider git://github.com/fulup-bzh/RangeSlider.git
```

### CODE REVIEW

**Comment by fulup-bzh** [comment]
Thank you very much for your contribution.

**Comment by fulup-bzh** [comment]
Note added you in the collab list, which should allow you to push directly your patches

**Comment by jfeigel** [comment]
Looks like the tag did not come over with the pull request. I went ahead and added the release and registered the repo with Bower.

```
 ❯ bower info bzm-range-slider                                                                                                 [06:07:43]
bower bzm-range-slider#*        cached git://github.com/fulup-bzh/RangeSlider.git#0.0.1
bower bzm-range-slider#*      validate 0.0.1 against git://github.com/fulup-bzh/RangeSlider.git#*

{
  name: 'bzm-range-slider',
  version: '0.0.1',
  description: 'Range Sliders for Angular & Foundation5',
  main: '/dist/bzm-range-slider.min.js',
  authors: [
    'Fulup Ar Foll <fulup@breizhme.net>'
  ],
  license: 'MIT',
  keywords: [
    'Angular',
    'Foundation',
    'Range',
    'Slider'
  ],
  homepage: 'https://github.com/fulup-bzh/RangeSlider',
  moduleType: [],
  dependencies: {},
  ignore: [
    '**/.*',
    'node_modules',
    'nbproject',
    'src',
    'Gruntfile.js',
    'MakeDist.sh'
  ]
}

Available versions:
  - 0.0.1

You can request info for a specific version with 'bower info bzm-range-slider#<version>'
```

**Comment by fulup-bzh** [comment]
```
On 21/03/16 12:08, James Feigel wrote:

. I went ahead and added the release and registered
  the repo with Bower.
You should have now a direct access to pushing patches, feel free to
move forward with your improvements.

Fulup
```

**Pull request merged**
